defaultBranch: 'develop'
branchName: '${issue.number}'
branches:
  - label: feature
    prefix: feature/
  - label: refactor
    prefix: refactor/
  - label: bug
    prefix: bugfix/
  - label: '*'
    prefix: issues/
autoCloseIssue: true
